# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-28 00:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='graphic_dependency',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='game',
            name='learning_curve',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='game',
            name='sound',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='game',
            name='linearity',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='game',
            name='replayability',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='game',
            name='review',
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='game',
            name='story',
            field=models.IntegerField(default=0),
        ),
    ]
