# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-28 23:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_auto_20160128_0013'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to=b''),
        ),
    ]
